version: '3'

services:
  postgres:
    image: 'postgres'
    container_name: 'team_project'
    ports:
      - 5222:5432
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=project'